In [2]:
import numpy as np

In [3]:
A = np.arange(25).reshape([5,5])
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
B = np.arange(27).reshape([3,3,3])
B

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [5]:
C = np.array([1,2,3])
C

array([1, 2, 3])

In [6]:
np.einsum('iii,i->i', B,C)

array([ 0, 26, 78])

In [7]:
np.einsum('ijk,i->jk', B,C)

array([[ 72,  78,  84],
       [ 90,  96, 102],
       [108, 114, 120]])

In [8]:
np.einsum('ijk,j->ik', B,C)

array([[ 24,  30,  36],
       [ 78,  84,  90],
       [132, 138, 144]])

In [10]:
phi = np.pi/4
np.einsum('ji,i->j', np.array([[np.cos(phi), -np.sin(phi)],[np.sin(phi), np.cos(phi)]]), np.array([1.,1.]))

array([1.11022302e-16, 1.41421356e+00])

## Matrix application on each vector (on axis 0) in a rank 3 tensor

In [20]:
vecs = np.zeros([2,2,1])
vecs[:,0,0] = [1.,1.]
vecs[:,1,0] = [0.,1.]
vecs

array([[[1.],
        [0.]],

       [[1.],
        [1.]]])

In [24]:
phi = np.pi/4
res = np.einsum('ji,ikl->jkl', np.array([[np.cos(phi), -np.sin(phi)],[np.sin(phi), np.cos(phi)]]), vecs)
print(res[:,0,0])
print(res[:,1,0])

[1.11022302e-16 1.41421356e+00]
[-0.70710678  0.70710678]
