In [36]:
import numpy as np

In [37]:
p = np.array([1.,1.,1.])
n_z = np.array([0.,0.,1.])
phi = np.pi/4

In [38]:
q_p = np.zeros(4)
q_p[1:] = p
q_p

array([0., 1., 1., 1.])

In [39]:
q_nz = np.array([np.cos(phi/2), *(np.sin(phi/2)*n_z)])
q_nz

array([0.92387953, 0.        , 0.        , 0.38268343])

In [40]:
def q_mult(q1, q2):
    w1, x1, y1, z1 = q1
    w2, x2, y2, z2 = q2
    w = w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2
    x = w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2
    y = w1 * y2 + y1 * w2 + z1 * x2 - x1 * z2
    z = w1 * z2 + z1 * w2 + x1 * y2 - y1 * x2
    return np.array([w, x, y, z])

In [41]:
def q_con(q):
    w, x, y, z = q
    return np.array((w, -x, -y, -z))

In [42]:
h = q_mult(q_nz, q_p)
h

array([-0.38268343,  0.5411961 ,  1.30656296,  0.92387953])

In [43]:
q_mult(h, q_con(q_nz))

array([ 0.00000000e+00, -1.11022302e-16,  1.41421356e+00,  1.00000000e+00])